// Code generated by mockery v2.43.1. DO NOT EDIT.

package transport

import (
	core "NureUvarenkoAnton/apzkr-pzpi-21-7-uvarenko-anton/Task2/apzkr-pzpi-21-7-uvarenko-anton-task2/internal/core"
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// mockIWalkService is an autogenerated mock type for the iWalkService type
type mockIWalkService struct {
	mock.Mock
}

// CreateWalk provides a mock function with given fields: ctx, walkParams
func (_m *mockIWalkService) CreateWalk(ctx context.Context, walkParams core.CreateWalkParams) error {
	ret := _m.Called(ctx, walkParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateWalk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.CreateWalkParams) error); ok {
		r0 = rf(ctx, walkParams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWalkInfoByWalkId provides a mock function with given fields: ctx, walkId
func (_m *mockIWalkService) GetWalkInfoByWalkId(ctx context.Context, walkId int64) (core.WalkInfo, error) {
	ret := _m.Called(ctx, walkId)

	if len(ret) == 0 {
		panic("no return value specified for GetWalkInfoByWalkId")
	}

	var r0 core.WalkInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (core.WalkInfo, error)); ok {
		return rf(ctx, walkId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) core.WalkInfo); ok {
		r0 = rf(ctx, walkId)
	} else {
		r0 = ret.Get(0).(core.WalkInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, walkId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalksByOwnerId provides a mock function with given fields: ctx, ownerID
func (_m *mockIWalkService) GetWalksByOwnerId(ctx context.Context, ownerID sql.NullInt64) ([]core.Walk, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalksByOwnerId")
	}

	var r0 []core.Walk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullInt64) ([]core.Walk, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullInt64) []core.Walk); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Walk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql.NullInt64) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalksByWalkerId provides a mock function with given fields: ctx, walkerID
func (_m *mockIWalkService) GetWalksByWalkerId(ctx context.Context, walkerID sql.NullInt64) ([]core.Walk, error) {
	ret := _m.Called(ctx, walkerID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalksByWalkerId")
	}

	var r0 []core.Walk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullInt64) ([]core.Walk, error)); ok {
		return rf(ctx, walkerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullInt64) []core.Walk); ok {
		r0 = rf(ctx, walkerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Walk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql.NullInt64) error); ok {
		r1 = rf(ctx, walkerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalksInfoByParams provides a mock function with given fields: ctx, params
func (_m *mockIWalkService) GetWalksInfoByParams(ctx context.Context, params core.GetWalkInfoByParamsParams) ([]core.WalkInfo, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetWalksInfoByParams")
	}

	var r0 []core.WalkInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.GetWalkInfoByParamsParams) ([]core.WalkInfo, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.GetWalkInfoByParamsParams) []core.WalkInfo); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.WalkInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.GetWalkInfoByParamsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWalkState provides a mock function with given fields: ctx, params
func (_m *mockIWalkService) UpdateWalkState(ctx context.Context, params core.UpdateWalkStateParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWalkState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.UpdateWalkStateParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockIWalkService creates a new instance of mockIWalkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIWalkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIWalkService {
	mock := &mockIWalkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
